### ISSUE TITLE
Stream Media Lightbox: Improvements

### ISSUE THREAD

**Issue by luke-** [humhub/humhub#6704]
- [ ]  When Higres Image - show downscaled version on fullscreen  (https://github.com/humhub/humhub/issues/6699)
- [ ]  Add Video Player (https://github.com/humhub/humhub/issues/6028)
- [ ]  Allow Zoom In on Mobile (https://github.com/humhub/humhub/issues/5310)
- [ ]  Add download button
- [ ] Check current "lightbox" gallery implementation should be migrated to another solution

**Comment by marc-farre** [comment]
Maybe we should take this opportunity to make it possible to add content addons (comment / like) in the lightbox?
See https://github.com/humhub-contrib/gallery/issues/46

**Comment by ArchBlood** [comment]
> This is a cool repo https://github.com/biati-digital/glightbox and it is MIT
> 
> Out-of-the-box, it supports playing videos (both embedded YT, VM, or local) and images with descriptions. However, with custom changes, the "description" area could be turned into a sidebar for comments and likes (maybe?).
> 
> Demo: https://biati-digital.github.io/glightbox/

I love the idea, although I'm not sure it should be quickly implement as they're still working on a v4 and this could require refactoring later on the development side of HumHub.

**Comment by marc-farre** [comment]
Should solve the issue when zooming into images of a gallery: https://community.humhub.com/comment/perma?id=49116
Related to https://github.com/humhub/humhub/issues/5310

**Comment by JK742020** [comment]
Hey Guys, I would really appreciate this development as soon as possible! There are quite a few things the lightbox which is used at the moment is not able to deal with.

ZOOM into picture without jumping to the next picture
displaying .heic
playing .m4a with different codecs
playing .mov on different devices (mac, chrome not working, mobile Android App, PWA working)

The exchange we have within our network is based on pictures (with the need to zoom), video- and audiofiles quite a lot. That's why I am really looking forward to have all this things working fine in the near future :)

**Comment by marc-farre** [comment]
As a reminder for later, when we replace the BlueImp gallery with another, we must update the mobile app:
https://github.com/humhub/app-internal/issues/47#issuecomment-2412283516

**Comment by JK742020** [comment]
Will this be part of 1.18. as well. I know many people worked a lot for all the other improvements coming in 1.18. And maybe the Ligthbox also has been changed?

**Comment by marc-farre** [comment]
It would be good if the new library could read audio messages.
Currently, if we record an audio on Android, the m4a file format is used, but there is no way to listen to it, you need to first download it...

<img width="380" height="213" alt="Image" src="https://github.com/user-attachments/assets/5488101c-3d00-4e71-8ae1-427955f2caee" />

**Comment by JK742020** [comment]
Will lightbox improvement be part of 1.19?
